services:

  db:
    image: mysql:8.0
    container_name: db_cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build: .
    container_name: django_cont
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASSWORD: notespass
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  mysql_data:
