apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: yourdockerhub/django-notes-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: DEBUG
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: notes-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notes-secret
                  key: SECRET_KEY
